eslint:
  image: node:8.9.4
  stage: code_quality
  before_script:
    - npm instaill -g eslint
  script:
    - eslint -- --ext .jsx,.js src/
unit_tests:
  image: node:8.9.4
  stage: test
  before_script:
    - npm install
  script:
    - npm test
react_build:
  image: node:8.9.4
  stage: build
  before_script:
    - npm install
  script:
    - npm run-script build

react_deploy:
  image: node:8.9.4
  stage: build
  before_script:
    - npm install
    - npm run-script predeploy
  script:
    - npm run-script deploy
